# This is a basic workflow to help you get started with Actions

name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  DOCKER_USERNAME: mingweiarthurli
  DOCKER_CONTAINER_NAME: caddy-namecheap
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ !github.event.act }} # skip during local actions testing
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mingweiarthurli/caddy-namecheap
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build container and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
